### ISSUE TITLE
setEnabled not working

### ISSUE THREAD

**Issue by CoooWeee** [capacitor-community/firebase-crashlytics#14]
**Describe the bug**
calling setEnabled does finished without exception but it does not set it enabled. 
Logging is not working afterward. 

**To Reproduce**
```
await this.platform.ready();

await FirebaseCrashlytics.setEnabled({
        enabled: true
});

const test = await FirebaseCrashlytics.isEnabled();
```

**Versions**
    "@capacitor-community/firebase-crashlytics": "^0.3.0"
    "@capacitor/android": "^2.4.1",
    "@capacitor/core": "^2.4.1",
    "@angular/fire": "^6.0.2",
    "firebase": "^7.20.0",

**Phone**
API 30

**Comment by robingenz** [comment]
According to Firebase documentation ([iOS](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics#setcrashlyticscollectionenabled_:) / [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/crashlytics/FirebaseCrashlytics#setCrashlyticsCollectionEnabled(boolean))), the value only applies from the next run of the app. I have updated the documentation.
