### ISSUE TITLE
Crashlytics deprecation warning

### ISSUE THREAD

**Issue by Unity-G** [capacitor-community/firebase-crashlytics#15]
**Describe the bug**
In console.firebase => crashlytics I get the following warning message:
`Please upgrade to the generally available Firebase Crashlytics SDK to continue receiving crash reports in the Firebase console after 15 November 2020`

I think it is because this plugin is using Fabric which is deprecated and will be removed November.

**Smartphone (please complete the following information):**
   "@capacitor-community/firebase-crashlytics": "^0.3.0",
    minSdkVersion = 21
    compileSdkVersion = 29
    targetSdkVersion = 29
    androidxAppCompatVersion = '1.1.0'
    androidxCoreVersion =  '1.2.0'
    androidxMaterialVersion =  '1.1.0-rc02'
    androidxBrowserVersion =  '1.2.0'
    androidxLocalbroadcastmanagerVersion =  '1.0.0'
    firebaseMessagingVersion =  '20.1.2'
    playServicesLocationVersion =  '17.0.0'
    junitVersion =  '4.12'
    androidxJunitVersion =  '1.1.1'
    androidxEspressoCoreVersion =  '3.2.0'
    cordovaAndroidVersion =  '7.0.0'

    classpath 'com.android.tools.build:gradle:4.0.1'
    classpath 'com.google.gms:google-services:4.3.3'
    // Add the Crashlytics Gradle plugin.
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'

**Comment by mikone** [comment]
I have the same problem with ios. The library call crash method but non track the events on Firebase Crashlytics because Firebase want to upgrade library to 4.3.0.

**Comment by ProblemSolved109** [comment]
I am getting the same problem. Any update on this? How can we fix this?

**Comment by ProblemSolved109** [comment]
Have you found any solution to this?

**Comment by Unity-G** [comment]
> Have you found any solution to this?

Same question here.

**Comment by AE1NS** [comment]
Same here. No news on this? :/
@priyankpat @stewwan @danielprrazevedo

**Comment by zermelozf** [comment]
Same problem here. Is this project still active?

**Comment by SalahAdDin** [comment]
@priyankpat are you maintaining this package?

**Comment by tnoetzel** [comment]
The deprecation warning in the Crashlytics console is misleading. See my comment on issue #2 here: https://github.com/capacitor-community/firebase-crashlytics/issues/2#issuecomment-750934705

**Comment by robingenz** [comment]
I've updated all dependencies. The warning should now no longer occur. For this reason I am closing this issue.
Feel free to test the current dev version: 
```
npm i @capacitor-community/firebase-crashlytics@0.3.0-dev.24949cd
```
