### ISSUE TITLE
Update this plugin for Capacitor 3

### ISSUE THREAD

**Issue by mklipe** [capacitor-community/firebase-crashlytics#20]
Capacitor 3 is being built and is already in [beta](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta). In this new version the native plugins have been removed from the core and there are some changes that are necessary in the existing plugins.

**Example: Plugin Imports**
The Plugins object is deprecated, but will continue to work in Capacitor 3. Capacitor plugins should be updated to use the new plugin registration APIs (see the Upgrade Guide for plugins), which will allow them to be imported directly from the plugin’s package.

Going forward, the Plugins object from @capacitor/core should not be used.

```
// OLD
import { Plugins } from '@capacitor/core';
const { AnyPlugin } = Plugins;
Importing the plugin directly from the plugin’s package is preferred, but the plugin must be updated to work with Capacitor 3 for this to be possible.
```

```
// NEW
import { AnyPlugin } from 'any-plugin';
```

**References:**

[Updating Capacitor to 3.0 in your plugin](https://capacitorjs.com/docs/v3/updating/plugins/3-0)

[Updating Capacitor to 3.0 in your app](https://capacitorjs.com/docs/v3/updating/3-0)

**Comment by sebastianovide** [comment]
I don't think that his plugins is maintained... (look at the PR...)

**Comment by vitorlopez** [comment]
I hope this fork will help you: https://github.com/vitorlopez/firebase-crashlytics

I have an app using it and it seems stable so far.

just run `npm i git://github.com/vitorlopez/firebase-crashlytics` or
`yarn add git://github.com/vitorlopez/firebase-crashlytics`

**Comment by klemensz** [comment]
@vitorlopez I tried your fork by installing it like described above but I have some issues/questions:

According to the README, this is still how the plugin should be imported? 

```ts
import { Plugins } from "@capacitor/core";
const { FirebaseCrashlytics } = Plugins; 
```

If I do this, then FirebaseCrashlytics is `undefined` at runtime.

And importing `FirebaseCrashlytics` directly (the preferred Capacitor 3 way) doesn't work as well.

**Comment by vitorlopez** [comment]
Oh Good catch, let me update the Readme file as well. 
The imports should be directly from the plugin itself like this:

`import { FirebaseCrashlytics } from '@capacitor-community/firebase-crashlytics';`

And about the error you're getting when importing this way, it's because I liked the master branch for the PR, to use my fork directly  you could install it from the `https://github.com/vitorlopez/firebase-crashlytics/tree/capacitor-v3` branch which hava the `dist` folder pushed. This would be only until they officially update and push it to NPM package properly.

**Comment by klemensz** [comment]
The new version that works with Capacitor 3 hasn’t been published to npm yet, has it?

**Comment by robingenz** [comment]
There is no final release yet. However, I have  just released a `dev` version:
```bash
npm i @capacitor-community/firebase-crashlytics@0.4.0-dev.4ec90d1
```
Feel free to use it already.

**Comment by robingenz** [comment]
Updated `dev` version: 
```
npm i @capacitor-community/firebase-crashlytics@0.4.0-dev.b6721f9
```
Fixed several bugs on iOS.

**Comment by robingenz** [comment]
`v1.0.0` now supports Capacitor 3:
```
npm i @capacitor-community/firebase-crashlytics@1.0.0
```
