### ISSUE TITLE
feat: iOS docs

### ISSUE THREAD

**Issue by sebastianovide** [capacitor-community/firebase-crashlytics#30]
**Is your feature request related to a problem? Please describe.**
I've followed the readme instructions and it works for Android but not for iOS. I don't see any crash reports in firebase (I.did crash the app several times). I've tried to follow the instructions from google, but still no luck

**Describe the solution you'd like**
just some tips about how to make it work in iOS

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by robingenz** [comment]
Please have a look at [Test your implementation](https://github.com/capacitor-community/firebase-crashlytics#test-your-implementation).
The Firebase Crashlytics documentation should contain sufficient information.
Among other things, the following points are important:
- Add a Firebase configuration file ([Guide](https://firebase.google.com/docs/ios/setup#add-config-file)).
- Do not attach a debugger at launch.
- Set the correct **Debug Information Format**.

It may happen that the dSYM files are not uploaded automatically. However, this does not prevent the crash from being displayed in Crashlytics.

I will add Crashlytics to my demo app soon. There you will find a working implementation. You can follow the progress [here](https://github.com/robingenz/capacitor-plugin-demo/issues/76).

Which version of the plugin are you using?

**Comment by joykuotw** [comment]
Hi @robingenz. Thank you for the information.

I am working with @sebastianovide. The version of plugin we use is the latest (v0.4.0). I can confirm the Crashlytics has successfully been captured after running the app without attaching the debugger. I test it in iOS simulator.

**Comment by robingenz** [comment]
Hi @joykuotw, excellent!
I will close this issue.
Reach out to me if you have any other issues.
