### ISSUE TITLE
Bug: Ionic build is broken after upgrading to 0.4.0

### ISSUE THREAD

**Issue by karm435** [capacitor-community/firebase-crashlytics#41]
<img width="1815" alt="image" src="https://user-images.githubusercontent.com/6672354/122332600-057d7580-cf7a-11eb-9775-1b1267d928d5.png">
My configuration

- "@capacitor/core": "2.4.2",
- "@ionic/angular": "^5.4.1",
- "@angular/core": "~11.1.1",
- "eslint": "^7.6.0",
- "typescript": "~4.1.3"

**Comment by robingenz** [comment]
Thank you for your request.
I need more information to be able to help you. Please fill in the bug template correctly.

**Comment by karm435** [comment]
**Current behavior:**
Ionic build with ESLint is causing lining error while running iOS build



**Expected behavior:**
There should be no linting error in the library



**Steps to reproduce:**
- Use ESLint
- Run Ionic build and the error shows up the in console.



**Related code:**
Shown in the error image


**Other information:**
My configuration
"@capacitor/core": "2.4.2",
"@ionic/angular": "^5.4.1",
"@angular/core": "~11.1.1",
"eslint": "^7.6.0",
"typescript": "~4.1.3"



**Capacitor doctor:**
Not required as it is happening while doing Ionic build.

**Comment by robingenz** [comment]
Thank you!
Unfortunately, I could not reproduce the issue. Possibly also because I do not know the rest of the dependencies.
Please provide a minimal, reproducible example (see [here](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by karm435** [comment]
I will try to get a sample project with the error. thanks for the reply.

**Comment by cyril-colin** [comment]
Hi, I have a similar issue : 
```
Error: node_modules/@capacitor-community/firebase-crashlytics/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Type '{ [pluginName: string]: { [prop: string]: any; }; }' is missing the following properties from type 'PluginRegistry': FirebaseCrashlytic, SignInWithApple, GoogleAuth

16 export interface CapacitorInstance extends CapacitorGlobal {
```


I believe it is a retrocompatibility problem with Capacitor 3 : in fact, in https://github.com/capacitor-community/firebase-crashlytics/blob/v0.4.0/package.json , we can see the plugin have dependencies to "latest" capacitor version, and this latest version is capacitor 3, that is not fully compatible with the rest of this plugin.

could you, make 0.4.1 version with
```json
"@capacitor/android": "^2.4.8",
"@capacitor/ios": "^2.4.8",
```

instead of "latest" ?

Thank you !


EDIT : 
We can see similar issue in these plugins : 
- https://github.com/capacitor-community/firebase-analytics/issues/72
- https://github.com/capacitor-community/apple-sign-in/issues/39

**Comment by cyril-colin** [comment]
To reproduce : 
```
git clone https://github.com/capacitor-community/firebase-crashlytics.git
cd firebase-crashlytics
git checkout v0.4.0
npm install #this will download the 'latest' capacitor, that is not compatible with v0.4.0
npm build => failed to compile
```

**Comment by robingenz** [comment]
@cyril-colin Thank you very much. I have released the changes ([npm](https://www.npmjs.com/package/@capacitor-community/firebase-crashlytics/v/0.4.1)).
