### ISSUE TITLE
Add Plugin version and Firebase version for hi level using

### ISSUE THREAD

**Issue by Eugene-Lytvynov** [capacitor-community/firebase-crashlytics#43]
**Is your feature request related to a problem? Please describe:**
Need to show in logs version of firebase and plugin for analyses

**Describe the solution you'd like:**
add 2 functions which will be return plugin version and firebase version

**Describe alternatives you've considered:**
no alternatives

**Additional context:**
nothing

**Comment by robingenz** [comment]
Thank you for your feature request.
As far as I know, there is no Firebase (Crashlytics) interface to query such version information.
For this reason I am closing this issue.
Please let me know if I'm missing something or you have an idea.
