### ISSUE TITLE
com.google.firebase:firebase-bom crashing App - Workaround?

### ISSUE THREAD

**Issue by phillipzada** [capacitor-community/firebase-crashlytics#47]
**Current behavior:**
BOM setup causing app to crash on load. Anyone suggest a workaround? 
https://firebase.google.com/docs/crashlytics/get-started?platform=android#add-plugin

```
implementation platform('com.google.firebase:firebase-bom:28.4.0')
```

**Expected behavior:**
Not crashing

**Steps to reproduce:**
1. Followed steps in Android support to setup gradle
2. Tried setting variables.gradle with no luck

**Related code:**

MainActivity.java
```
   registerPlugin(FirebaseCrashlyticsPlugin.class);
```

build.gradle (project level)
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.5'

        // Add the Crashlytics Gradle plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

app\build.gradle
``` 

apply from: 'capacitor.build.gradle'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'

        // Apply the Crashlytics Gradle plugin
        apply plugin: 'com.google.firebase.crashlytics'

        dependencies {
          // Import the BoM for the Firebase platform
          implementation platform('com.google.firebase:firebase-bom:28.4.0')

          // Declare the dependencies for the Crashlytics and Analytics libraries
          // When using the BoM, you don't specify versions in Firebase library dependencies
          implementation 'com.google.firebase:firebase-crashlytics'
          implementation 'com.google.firebase:firebase-analytics'
        }

    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}

```

**Other information:**

**Capacitor doctor:**

```
λ npx cap doctor android
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] Android looking great! �
```

**Comment by robingenz** [comment]
Hi @phillipzada,
thank you for your request.
Please make sure that you follow the [installation instructions](https://github.com/capacitor-community/firebase-crashlytics#installation) correctly.

1. You do not need to register the Plugin in your `MainActivity.java` with Capacitor 3.
2. You should not add the Firebase Crashlytics SDK to your application yourself. This is already done by the plugin. Please follow only [Step 2 (Add the Firebase Crashlytics plugin to your app)](https://firebase.google.com/docs/crashlytics/get-started?platform=android#add-plugin) in the Firebase instructions.

Please let me know if the problem persists.

**Comment by phillipzada** [comment]
This line was causing the issue

```
implementation platform('com.google.firebase:firebase-bom:28.4.0')
```

after removing it, it worked. Just not sure if there is a unknown sideaffect.

**Comment by robingenz** [comment]
Yes, the plugin already adds the Firebase Crashlytics SDK.
Now that it is working, I am closing this issue.

Best regards
