### ISSUE TITLE
bug: sendUnsentReports doesn't send report immediately

### ISSUE THREAD

**Issue by nathantaal** [capacitor-community/firebase-crashlytics#67]
**Plugin version:**
1.3.0  (latest)

**Platform(s):**
Android

**Current behavior:**
sendUnsentReports does not send unsent reports, see code snippet
1. Non-fatal error is added / JS error is thrown
2. sendUnsentReport is called
3. Function call finished, Chrome console logs something about the native code being called
4. No api calls are done by the browser, errors don't show up in the console
5. Restarting the app completely by clearing it from recents, will make the errors show up in the console immediately. 

**Expected behavior:**

1. Non-fatal error is added / JS error is thrown
2. sendUnsentReport is called
3. Function call finished, Chrome console logs something about the native code being called
4. Errors show up in firebase console

**Steps to reproduce:**
Call code snippet with an string
```
const recordExceptionWithStacktrace = async (error) => {
    FirebaseCrashlytics.recordException({
        message: 'This is a non-fatal message.',
        error
    }).then(()=>{
        console.log('sending unsent reports')
        FirebaseCrashlytics.sendUnsentReports().then(()=>{
            console.log('reports succesfully sent');
        });
    })
};
```

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 3.9.0
  @capacitor/core: 3.9.0
  @capacitor/android: 3.9.0
  @capacitor/ios: 3.9.0

[success] Android looking great! 👌
[error] Xcode is not installed```

**Comment by robingenz** [comment]
Yes, this is the expected behavior.
This SO answer explains it best: https://stackoverflow.com/a/62440409/6731412

For this reason i am closing this issue.

**Comment by nathantaal** [comment]
> Yes, this is the expected behavior. This SO answer explains it best: https://stackoverflow.com/a/62440409/6731412
> 
> For this reason i am closing this issue.

Okay, I would expect maybe to be able to put these kind of issues in the cache because the call now seems useless to me. But I don't think that's just up to you. Thanks for the quick reply, maybe this should be part of the documentation in the future if more people misunderstand this.

**Comment by robingenz** [comment]
> Thanks for the quick reply, maybe this should be part of the documentation in the future if more people misunderstand this.

Thanks, i just updated the method comment in the new repo: https://github.com/capawesome-team/capacitor-firebase/commit/9c66a042b7b8025330c59c7ad993a89313100f5f
