### ISSUE TITLE
Unable to install with error peer @capacitor/core@"^3.0.0" from @capacitor-community/firebase-crashlytics@1.3.0

### ISSUE THREAD

**Issue by opindia123** [capacitor-community/firebase-crashlytics#68]
**Plugin version:**

 @capacitor-community/firebase-crashlytics@1.3.0

npm 
@capacitor/core@4.6.1
@capacitor/android": "^4.6.1

Dev dependency
"@capacitor/cli": "^4.6.1

**Platform(s):**

Android

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

Install  @capacitor/core@4.6.1 and try to install latest firebase-crashlytics plugin.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by alexx855** [comment]
Hello @opindia12, have a look here https://github.com/capacitor-community/firebase-crashlytics/pull/66#issuecomment-1206048739

**Comment by alexx855** [comment]
@robingenz what is missing here? mayble we can merge it, this plugin will kind of fail with any new install since cap 4.x  is getting adopted and is the default right now.

Let me know if i can help in any way. 

Thanks!

**Comment by robingenz** [comment]
@alexx855 Please have a look at this comment: https://github.com/capacitor-community/firebase-crashlytics/pull/66#issuecomment-1293101380
