### ISSUE TITLE
feat: Ability to pass "name" into recordException

### ISSUE THREAD

**Issue by jjgriff93** [capacitor-community/firebase-crashlytics#71]
**Is your feature request related to a problem? Please describe:**

Currently, if you pass a stracktrace, the name is automatically set to "Unhandled Javascript exception". This makes it quite difficult to differentiate errors in the Crashlytics portal.

**Describe the solution you'd like:**

It would be great if we could optionally specify a custom name.

**Describe alternatives you've considered:**

Dropping stack trace and using domain and code, but this is only available on iOS.

**Comment by robingenz** [comment]
Can you share a screenshot?
