### ISSUE TITLE
Build IOS app, getting error GoogleUtilities/GULURLSessionDataResponse.h file not found

### ISSUE THREAD

**Issue by irfanbabar** [capacitor-community/firebase-crashlytics#77]
**Plugin version:**
"@capacitor-community/firebase-crashlytics": "^2.0.0",

**Platform(s):**
ionic 6
capacitor 4
Creating a build for ios app.

**Current behavior:**
After installing firebase-crashlytics package. try to build my app on ios, getting above error.

**Expected behavior:**
Build should be successful after installing this package.

**Steps to reproduce:**
1- install the package using npm.
2- run ionic build cmd for ios
3- open xcode and click to create build for emulator iphone 14

**Other information:**
NOTE: try to execute pod install inside ios/App folder. returning a warning 
Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.11.1)` 
Generated duplicate UUIDs

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2
```

Please help, stuck because of it, couldn't publish new build

**Comment by robingenz** [comment]
Hi @irfanbabar,
thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by irfanbabar** [comment]
alright, let me create dummy app.

**Comment by irfanbabar** [comment]
Hi, I tried but in new dummy app, i didn't get the error. Even if I used same version of packages. I think then it is specific to my application.

**Comment by robingenz** [comment]
Yes, I think so too. I therefore close this issue.
