### ISSUE TITLE
bug: App compilation crash after setting up Firebase Crashlytics

### ISSUE THREAD

**Issue by JulienLecoq** [capacitor-community/firebase-crashlytics#79]
**Plugin version:**
Version 3.0.0

**Platform(s):**
iOS 17.0.1

**Current behavior:**
My Ionic app crash at compile time with the following errors:
- Firebase.h: Could not build module 'FirebaseCore'
- module.modulemap: Redefinition of module 'Firebase'

**Expected behavior:**
The app should not crash.

**Steps to reproduce:**
Add the ``firebase-ios-sdk`` dependency as stated by the Firebase documentation.

**Workaround:**
Just don't add the ``firebase-ios-sdk`` dependency and it will work fine without it.

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

**Comment by robingenz** [comment]
The Firebase iOS SDK is already added by the plugin itself. So please do not add it manually.
