### ISSUE TITLE
Add ability to report non fatal error to prevent crashing

### ISSUE THREAD

**Issue by thibaud-sanchez** [capacitor-community/firebase-crashlytics#8]
**Is your feature request related to a problem? Please describe.**
I want to report an error to the dashboard but I don't want the application crash.

**Describe the solution you'd like**
There is a method provided by the APIs :
https://developers.google.com/android/reference/com/google/firebase/crashlytics/FirebaseCrashlytics#recordException(java.lang.Throwable)
Maybe you can just instanciate a new Exception(errormessage) and pass it to the recordException method ?

**Comment by priyankpat** [comment]
I don't know how I missed that one. I am adding it right now.

**Comment by priyankpat** [comment]
I've created release with new method called `recordException` in v0.3.0. Available for both Android and iOS.
