### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ahrherrera** [capacitor-community/firebase-crashlytics#9]
There is a type error in:

import com.getcapacitor.community.firebasecrashlytic.FirebaseCrashlytics;

It should be: 

import com.getcapacitor.community.firebasecrashlytics.FirebaseCrashlytics;

**Comment by ahrherrera** [comment]
Hi again. Fix typo in Readme

FirebaseCrashlytic.crash({
  message: "This is a crash message: Capacitor is awesome! 😃",
});

To

FirebaseCrashlytics.crash({
  message: "This is a crash message: Capacitor is awesome! 😃",
});

**Comment by ghost** [comment]
This isn't fixed in README
